### PR TITLE
refactor: remove unnecessary code

### PR DESCRIPTION
**Pull request by sabotagebeats**
fix unneccesary code stub

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]

**Review by fubuloubu — APPROVED** [review]

**Comment by fubuloubu** [comment]
@sabotagebeats seems like there was a test failure that maybe relevant to fix?

**Comment by sabotagebeats** [comment]
@fubuloubu the test failure points to this code within ape, so I've made an issue here: 
https://github.com/ApeWorX/ape-vyper/issues/13

should I revert the merge?

**Comment by sabotagebeats** [comment]
I will revert merge for now and then when https://github.com/ApeWorX/ape-vyper/issues/13 is fixed then we can re run the tests and then merge this once all test pass.

**Comment by sabotagebeats** [comment]
thank you :) @fubuloubu

**Pull request merged**
